---
# Builds our RPM for tagged releases only
name: ias_rpm_release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  my_job:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo $PWD
      - run: ls
      - run: echo "ðŸ This job's status is ${{ job.status }}."

      - name: Get the tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Install deps
        run: dnf install -y rpm-build
      - name: Build package
        run: bash -x extra/ias.rpmbuild.sh $TAG_NAME
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpmbuild/RPMS/noarch/simplesamlphp-${{ github.ref }}-1.noarch.rpm
            rpmbuild/SOURCES/noarch/simplesamlphp-${{ github.ref }}.tar.gz
